language: python
os: "ubuntu" # set the system

matrix:
  include:
    - python: 3.6
    - python: 3.7
    - python: 3.8

script:
  - sudo python setup.py install

before_install:
  - sudo locale-gen zh_CN.GB18030
  - sudo apt install gcc
  - sudo python -m pip install --upgrade --force-reinstall setuptools